### ISSUE TITLE
Number of documents displayed in Overview tab is higher than index size

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [mobz/elasticsearch-head#257]
I just updated my index with new fields, some of which are nested. Therefore there are a lot of (hidden) nested documents created, according to the documentation. 

Does the plugin only display the number of documents (current and deleted), or additionally to that, the number of nested documents too?

The actual document number if around 200,000 and the new one is 4,100,000.

**Comment by philipskokoh** [comment]
Yes. It includes the number of nested documents since that is the number you get from indices stats API.
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-stats.html

If you want exact number of root docs, then you have to an elasticsearch query. MatchAll Query is good enough to get the number.
